version: '3.9'
services:
    payara:
        container_name: payara
        build: .
        image: my-payara:latest
        user: root
        environment:
        - PAYARA_ARGS=--debug
        - PREBOOT_COMMANDS=/pre-boot.txt
        ports:
         - "48080:8080"
         - "48181:8181"
         - "48443:8443"
         - "44848:4848"
         - "49009:9009"
        volumes:
        - ./pre-boot.txt:/pre-boot.txt
    mydb:
        container_name: mydb
        image: postgres:9.6-alpine
        environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        ports:
        - "45432:5432"
        volumes:
        - my-datavolume:/var/lib/postgresql/data
volumes:
  my-datavolume:

